In [1]:
import numpy as np

In [2]:
v1=np.array([[1, 2, 3],[4,5,6]])
v2=np.array([[7, 8, 9],[10,11,12]])

In [3]:
np.percentile(v1,99)

np.float64(5.95)

In [3]:
v1+v2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [7]:
np.dot(v1,v2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [6]:
v1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
np.linalg.det([[1, 2], [3, 4]])

np.float64(-2.0000000000000004)

In [10]:
np.linalg.eig([[1, 2], [3, 4]])

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [16]:
a=np.array([[1,2],[3,5]])
a

array([[1, 2],
       [3, 5]])

In [17]:
np.linalg.inv(a)

array([[-5.,  2.],
       [ 3., -1.]])

In [18]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.16227766,  6.16227766]), eigenvectors=array([[-0.86460354, -0.36126098],
       [ 0.50245469, -0.93246475]]))

In [20]:
np.linalg.solve(a,[[6,7],[8,9]])

array([[-14., -17.],
       [ 10.,  12.]])

In [21]:
np.linalg.svd(a)

SVDResult(U=array([[-0.35737275, -0.93396184],
       [-0.93396184,  0.35737275]]), S=array([6.24294338, 0.16018085]), Vh=array([[-0.50605269, -0.86250257],
       [ 0.86250257, -0.50605269]]))

<h1>delete it after some time

In [1]:
import pandas as pd
da={'ID':[1,2,3],'Name':['Alice','Bob','Charlie'],'Age':[25,30,35]}
df=pd.DataFrame(da)
df.head()

   ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35

In [2]:
df['Age']=df['Age'].astype(float)

In [23]:
df

   ID     Name   Age
0   1    Alice  25.0
1   2      Bob  30.0
2   3  Charlie  35.0

In [3]:
import numpy as np

In [5]:
d={'id':[1,2,3,4,5],'values':[10,np.nan,30,np.nan,60]}
df1=pd.DataFrame(d)
df1

   id  values
0   1    10.0
1   2     NaN
2   3    30.0
3   4     NaN
4   5    60.0

In [7]:
df1.fillna(df1['values'].mean(), inplace=True)

In [8]:
df1

   id     values
0   1  10.000000
1   2  33.333333
2   3  30.000000
3   4  33.333333
4   5  60.000000

In [9]:
dat={'stu_id':[12,34,35,45],'stu_marks':[24,35,34,35]}
df2=pd.DataFrame(dat)

In [17]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler=MinMaxScaler()
std_scaler=StandardScaler()

In [20]:
df2['minmaxscaler']=scaler.fit_transform(df2[['stu_marks']])

In [21]:
df2['standard']=std_scaler.fit_transform(df2[['stu_marks']])

In [22]:
df2

   stu_id  stu_marks  minmaxscaler  standard
0      12         24      0.000000 -1.725324
1      34         35      1.000000  0.646997
2      35         34      0.909091  0.431331
3      45         35      1.000000  0.646997