In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\salaries.csv")

In [2]:
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [13]:
input=df[['company','job','degree']]
target=df['salary_more_then_100k']

In [14]:
input.head()

  company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()
#create new columns for encoded values (categorical to numerical)

In [ ]:
input['company_n']=le_company.fit_transform(input['company'])
input['job_n']=le_job.fit_transform(input['job'])
input['degree_n']=le_degree.fit_transform(input['degree'])

In [17]:
input.drop(['company','job','degree'],axis='columns',inplace=True)

In [24]:
input.sample(5)

    company_n  job_n  degree_n
10          1      2         0
0           2      2         0
1           2      2         1
2           2      0         0
5           2      1         1

In [18]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [19]:
model.fit(input,target)

DecisionTreeClassifier()

In [21]:
model.predict([[1,0,2]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [25]:
model.predict([[2,0,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [26]:
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\titanic.csv")
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
416,417,1,2,"Drew, Mrs. James Vivian (Lulu Thorne Christian)",female,34.0,1,1,28220,32.500,NaN,S
328,329,1,3,"Goldsmith, Mrs. Frank John (Emily Alice Brown)",female,31.0,1,1,363291,20.525,NaN,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.000,B51 B53 B55,S
256,257,1,1,"Thorne, Mrs. Gertrude Maybelle",female,NaN,0,0,PC 17585,79.200,NaN,C
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.525,NaN,S

In [56]:
input=df[['Pclass','Sex','Age','Fare']]
target=df['Survived']

In [57]:
le_sex=LabelEncoder()

In [58]:
input['Sex_n']=le_sex.fit_transform(input['Sex'])

C:\Users\Jeevan kumar\AppData\Local\Temp\ipykernel_5100\1341401460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input['Sex_n']=le_sex.fit_transform(input['Sex'])

In [50]:
input.head()

   Pclass     Sex   Age     Fare  Sex_n
0       3    male  22.0   7.2500      1
1       1  female  38.0  71.2833      0
2       3  female  26.0   7.9250      0
3       1  female  35.0  53.1000      0
4       3    male  35.0   8.0500      1

In [59]:
input.drop(['Sex'],axis='columns',inplace=True)

C:\Users\Jeevan kumar\AppData\Local\Temp\ipykernel_5100\3833701802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input.drop(['Sex'],axis='columns',inplace=True)

In [68]:
input.sample(5)

     Pclass   Age      Fare  Sex_n
147       3   9.0   34.3750      0
282       3  16.0    9.5000      1
795       2  39.0   13.0000      1
210       3  24.0    7.0500      1
31        1   NaN  146.5208      0

In [53]:
model=DecisionTreeClassifier()

In [61]:
model.fit(input,target)

DecisionTreeClassifier()

In [63]:
model.predict([[2,34,250,1]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [74]:
model.predict([[1,34,347,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])