In [1]:
import pandas as pd
from sklearn.svm import SVC
from sklearn.datasets import load_iris
iris=load_iris()

In [2]:
df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
df['target']=iris.target
df['target']=df['target'].apply(lambda x:iris.target_names[x])

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [4]:
df[42:56]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
42,4.4,3.2,1.3,0.2,setosa
43,5.0,3.5,1.6,0.6,setosa
44,5.1,3.8,1.9,0.4,setosa
45,4.8,3.0,1.4,0.3,setosa
46,5.1,3.8,1.6,0.2,setosa
47,4.6,3.2,1.4,0.2,setosa
48,5.3,3.7,1.5,0.2,setosa
49,5.0,3.3,1.4,0.2,setosa
50,7.0,3.2,4.7,1.4,versicolor
51,6.4,3.2,4.5,1.5,versicolor
52,6.9,3.1,4.9,1.5,versicolor
53,5.5,2.3,4.0,1.3,versicolor
54,6.5,2.8,4.6,1.5,versicolor
55,5.7,2.8,4.5,1.3,versicolor

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.3)

In [6]:
model=SVC(kernel='rbf',C=1,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [7]:
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=3,return_train_score=False)

clf.fit(X_train,y_train)
clf.cv_results_

{'mean_fit_time': array([0.00144196, 0.00112645, 0.00148098, 0.00174673, 0.00144569,
        0.00143631]),
 'std_fit_time': array([6.64157308e-05, 2.34607866e-05, 3.11492837e-04, 3.04307568e-04,
        1.32240355e-04, 3.46163215e-04]),
 'mean_score_time': array([0.00110896, 0.00103394, 0.00122277, 0.00127618, 0.00151491,
        0.00109347]),
 'std_score_time': array([9.50383097e-05, 1.44439468e-04, 2.30615834e-04, 1.01490607e-04,
        6.45773112e-04, 1.65510163e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split1_test_score': array([0.88571429, 0.94285714, 0.88571429, 0.88571429, 0.88571429,
        0.88571429]),
 'split2_test_score': array([0.94285714, 0.91428571, 0.91428571, 0.91428571, 0.88571429,
        0.91428571]),
 'mean_test_score': array([0.94285714, 0.95238095, 0.93333333, 0.93333333, 0.92380952,
        0.93333333]),
 'std_test_score': array([0.04665695, 0.03563483, 0.04856209, 0.04856209, 0.0538748 ,
        0.04856209]),
 'rank_test_score': array([2, 1, 3, 3, 6, 3], dtype=int32)}

In [8]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [9]:
clf.best_score_

np.float64(0.9523809523809524)

In [10]:
cdf=pd.DataFrame(clf.cv_results_)

In [11]:
cdf.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001442,0.000066,0.001109,0.000095,1,rbf,"{'C': 1, 'kernel': 'rbf'}",1.0,0.885714,0.942857,0.942857,0.046657,2
1,0.001126,0.000023,0.001034,0.000144,1,linear,"{'C': 1, 'kernel': 'linear'}",1.0,0.942857,0.914286,0.952381,0.035635,1
2,0.001481,0.000311,0.001223,0.000231,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.0,0.885714,0.914286,0.933333,0.048562,3
3,0.001747,0.000304,0.001276,0.000101,10,linear,"{'C': 10, 'kernel': 'linear'}",1.0,0.885714,0.914286,0.933333,0.048562,3
4,0.001446,0.000132,0.001515,0.000646,20,rbf,"{'C': 20, 'kernel': 'rbf'}",1.0,0.885714,0.885714,0.923810,0.053875,6

In [12]:
cdf[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.942857
1        1       linear         0.952381
2       10          rbf         0.933333
3       10       linear         0.933333
4       20          rbf         0.923810
5       20       linear         0.933333

In [13]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_run_search',
 '_select_best_index',
 '_sk_visual_block_',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_metadata_routing',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'refit',
 'refit_time_',
 'return_train_score',
 'score',
 'score_samples',
 'scorer_',
 'scoring',
 'set_params',
 'transform',
 'verbose']

In [14]:
from sklearn.model_selection import RandomizedSearchCV
rd=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20,30,40,50],
    'kernel':['rbf','linear']
},cv=3,n_iter=4,return_train_score=False)
rd.fit(X_train,y_train)
rd.cv_results_

{'mean_fit_time': array([0.00148511, 0.00132306, 0.00152453, 0.00142638]),
 'std_fit_time': array([0.00025569, 0.00036006, 0.00021016, 0.0001796 ]),
 'mean_score_time': array([0.00122746, 0.00088644, 0.00137973, 0.00094366]),
 'std_score_time': array([3.59169569e-04, 1.59391454e-04, 7.15075576e-05, 1.47443082e-04]),
 'param_kernel': masked_array(data=['linear', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[30, 10, 40, 50],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 30},
  {'kernel': 'linear', 'C': 10},
  {'kernel': 'rbf', 'C': 40},
  {'kernel': 'linear', 'C': 50}],
 'split0_test_score': array([1., 1., 1., 1.]),
 'split1_test_score': array([0.88571429, 0.88571429, 0.88571429, 0.85714286]),
 'split2_test_score': array([0.91428571, 0.91428571, 0.88571429, 0.91428571]),
 'mean_test_score': array([0.93333333, 0.93333333, 0.92380952, 0.92380952]),
 'std_test_score': array([0.04856209, 0.04856209, 0.0538748 , 0.0587087 ]),
 'rank_test_score': array([1, 1, 3, 3], dtype=int32)}

In [15]:
rd.best_params_

{'kernel': 'linear', 'C': 30}

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm

In [26]:
model_params={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model':LogisticRegression(max_iter=500),
        'params':{
            'C':[1,5,10]
        }
    },
    'GaussianNB':{
        'model':GaussianNB(),
        'params':{
            }
    },
    'MultinomialNB':{
        'model':MultinomialNB(),
        'params':{
            'alpha':[0.1,0.5,1.0]
        }
    },
    'DecisionTreeClassifier':{
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion':['gini','entropy']
        }
    }
}

In [21]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [27]:
Score_list=[]

for model_name,mp in model_params.items():
    clf=GridSearchCV(mp['model'],mp['params'],cv=3,return_train_score=False)
    clf.fit(X_train,y_train)
    Score_list.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

In [28]:
df=pd.DataFrame(Score_list)

In [29]:
df

                    model  best_score                   best_params
0                     svm    0.952381  {'C': 1, 'kernel': 'linear'}
1           random_forest    0.923810           {'n_estimators': 5}
2     logistic_regression    0.933333                      {'C': 1}
3              GaussianNB    0.923810                            {}
4           MultinomialNB    0.942857                {'alpha': 0.1}
5  DecisionTreeClassifier    0.923810         {'criterion': 'gini'}