In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\titanic.csv")
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.0,1,0,PC 17761,106.4250,C86,C
669,670,1,1,"Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)",female,NaN,1,0,19996,52.0000,C126,S
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
235,236,0,3,"Harknett, Miss. Alice Phoebe",female,NaN,0,0,W./C. 6609,7.5500,NaN,S

In [ ]:
df.drop(['PassengerId','Name','Parch','SibSp','Ticket','Cabin','Embarked'],axis=1,inplace=True)

In [3]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
x=df.drop(['Survived','Sex'],axis=1)
y=df['Survived']

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le_Sex=LabelEncoder()
df['le_Sex']=le_Sex.fit_transform(df['Sex'])

In [7]:
x.columns[x.isnull().any()]

Index(['Age'], dtype='str')

In [8]:
x.Age=x.Age.fillna(x['Age'].median())
x.sample(5)

     Pclass   Age     Fare
631       3  51.0   7.0542
285       3  33.0   8.6625
551       2  27.0  26.0000
398       2  23.0  10.5000
10        3   4.0  16.7000

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [12]:
model.fit(x_train,y_train)

GaussianNB()

In [13]:
model.score(x_test,y_test)

0.6536312849162011

In [15]:
model.predict_proba(x_test[:10])

array([[0.50723501, 0.49276499],
       [0.8806218 , 0.1193782 ],
       [0.18491637, 0.81508363],
       [0.77818915, 0.22181085],
       [0.87952518, 0.12047482],
       [0.66339945, 0.33660055],
       [0.86360177, 0.13639823],
       [0.28038798, 0.71961202],
       [0.883931  , 0.116069  ],
       [0.82355589, 0.17644411]])

# working with different data set

In [ ]:
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\spam.csv")
df.sample(5)

In [ ]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Category']=le.fit_transform(df['Category'])
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
from sklearn.model_selection import train_test_split
x=df['Message']
y=df['Category']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
v=CountVectorizer()
X_train=v.fit_transform(x_train)
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7538))

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model_nv=MultinomialNB()

In [ ]:
model_nv.fit(X_train,y_train)

MultinomialNB()

In [ ]:
model_nv.score(v.transform(x_test),y_test)

0.9856424982053122

In [ ]:
e=["Congratulations! You've won a $1,000 Walmart gift card. Click here to claim your prize.",
   "Hey, are we still meeting for lunch today?"]
model_nv.predict(v.transform(e))

array([1, 0])

In [ ]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),
              ('naive_bayes',MultinomialNB())])

In [ ]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('naive_bayes', MultinomialNB())])

In [ ]:
clf.score(x_test,y_test)

0.9856424982053122

In [ ]:
clf.predict(e)

array([1, 0])

<h1>random pratices

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
# input['le_Sex']=le.fit_transform(input['Sex'])
df['le_Sex'] = le.fit_transform(df['Sex'])

In [ ]:
df['le_Embarked']=le.fit_transform(df['Embarked'])

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,le_Sex
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [ ]:
X = df[['Pclass', 'Age', 'SibSp', 'le_Sex', 'le_Embarked', 'Parch', 'Fare']]
y=df['Survived']

In [ ]:
X

     Pclass   Age  SibSp  le_Sex  le_Embarked  Parch     Fare
0         3  22.0      1       1            2      0   7.2500
1         1  38.0      1       0            0      0  71.2833
2         3  26.0      0       0            2      0   7.9250
3         1  35.0      1       0            2      0  53.1000
4         3  35.0      0       1            2      0   8.0500
..      ...   ...    ...     ...          ...    ...      ...
886       2  27.0      0       1            2      0  13.0000
887       1  19.0      0       0            2      0  30.0000
888       3   NaN      1       0            2      2  23.4500
889       1  26.0      0       1            0      0  30.0000
890       3  32.0      0       1            1      0   7.7500

[891 rows x 7 columns]

In [ ]:
cross_val_score(DecisionTreeClassifier(),X,y)

array([0.73743017, 0.78651685, 0.80898876, 0.75280899, 0.79213483])

In [ ]:
cross_val_score(RandomForestClassifier(),X,y)

array([0.76536313, 0.80898876, 0.84269663, 0.7752809 , 0.8258427 ])

In [ ]:
from sklearn.datasets import load_wine
data=load_wine()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets  import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection  import train_test_split