In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\titanic.csv")
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.4750,NaN,S
281,282,0,3,"Olsson, Mr. Nils Johan Goransson",male,28.0,0,0,347464,7.8542,NaN,S
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S
514,515,0,3,"Coleff, Mr. Satio",male,24.0,0,0,349209,7.4958,NaN,S
91,92,0,3,"Andreasson, Mr. Paul Edvin",male,20.0,0,0,347466,7.8542,NaN,S

In [2]:
df.drop(['PassengerId','Name','Parch','SibSp','Ticket','Cabin','Embarked'],axis=1,inplace=True)
# df.drop(['le_Sex','le_Embarked'],axis=1,inplace=True)

In [3]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
x=df.drop(['Survived','Sex'],axis=1)
y=df['Survived']

In [5]:
le_Sex=LabelEncoder()
df['le_Sex']=le_Sex.fit_transform(df['Sex'])

NameError: name 'LabelEncoder' is not defined

In [ ]:
x.columns[x.isnull().any()]

Index([], dtype='object')

In [ ]:
x.Age=x.Age.fillna(x['Age'].median())
x.sample(5)

     Pclass   Age     Fare  le_Sex
196       3  28.0   7.7500       1
845       3  42.0   7.5500       1
415       3  28.0   8.0500       0
474       3  22.0   9.8375       0
333       3  16.0  18.0000       1

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [ ]:
model.fit(x_train,y_train)

GaussianNB()

In [ ]:
model.score(x_test,y_test)

0.7653631284916201

In [ ]:
model.predict([[2,22.0,65.23,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
cross_val_score(GaussianNB(),x,y)

array([0.70949721, 0.79775281, 0.78089888, 0.76404494, 0.79213483])

In [ ]:
model.predict([[2,22.0,65.23,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
model.predict_proba([[2,22.0,65.23,0]])

C:\Users\Jeevan kumar\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([[0.10795031, 0.89204969]])

In [ ]:
model.predict_proba(x_test[:10])

array([[0.96528086, 0.03471914],
       [0.96974686, 0.03025314],
       [0.31817731, 0.68182269],
       [0.9388549 , 0.0611451 ],
       [0.47133126, 0.52866874],
       [0.96849891, 0.03150109],
       [0.96786939, 0.03213061],
       [0.31001637, 0.68998363],
       [0.97003703, 0.02996297],
       [0.96979832, 0.03020168]])

In [6]:
df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\spam.csv")
df.sample(5)

     Category                                            Message
3547      ham  SO IS TH GOWER MATE WHICH IS WHERE I AM!?! HOW...
5121      ham                   Oops I did have it,  &lt;#&gt; ?
3072      ham     Apart from the one i told you about yesterday?
1453      ham                  That's good, because I need drugs
2834     spam  You've won tkts to the EURO2004 CUP FINAL or £...

In [7]:
df.groupby('Category').describe()

         Message                                                            \
           count unique                                                top
Category
ham         4825   4516                             Sorry, I'll call later
spam         747    641  Please call our customer service representativ...


         freq
Category
ham        30
spam        4

In [8]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Category']=le.fit_transform(df['Category'])
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

In [11]:
from sklearn.model_selection import train_test_split
x=df['Message']
y=df['Category']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
v=CountVectorizer()
X_train=v.fit_transform(x_train)
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7538))

In [14]:
from sklearn.naive_bayes import MultinomialNB
model_nv=MultinomialNB()

In [15]:
model_nv.fit(X_train,y_train)

MultinomialNB()

In [16]:
model_nv.score(v.transform(x_test),y_test)

0.9856424982053122

In [17]:
e=["Congratulations! You've won a $1,000 Walmart gift card. Click here to claim your prize.",
   "Hey, are we still meeting for lunch today?"]
model_nv.predict(v.transform(e))

array([1, 0])

In [22]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),
              ('naive_bayes',MultinomialNB())])

In [23]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('naive_bayes', MultinomialNB())])

In [24]:
clf.score(x_test,y_test)

0.9856424982053122

In [25]:
clf.predict(e)

array([1, 0])

<h1>random pratices

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [20]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [21]:
# input['le_Sex']=le.fit_transform(input['Sex'])
df['le_Sex'] = le.fit_transform(df['Sex'])

KeyError: 'Sex'

In [ ]:
df['le_Embarked']=le.fit_transform(df['Embarked'])

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,le_Sex
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [ ]:
X = df[['Pclass', 'Age', 'SibSp', 'le_Sex', 'le_Embarked', 'Parch', 'Fare']]
y=df['Survived']

In [ ]:
X

     Pclass   Age  SibSp  le_Sex  le_Embarked  Parch     Fare
0         3  22.0      1       1            2      0   7.2500
1         1  38.0      1       0            0      0  71.2833
2         3  26.0      0       0            2      0   7.9250
3         1  35.0      1       0            2      0  53.1000
4         3  35.0      0       1            2      0   8.0500
..      ...   ...    ...     ...          ...    ...      ...
886       2  27.0      0       1            2      0  13.0000
887       1  19.0      0       0            2      0  30.0000
888       3   NaN      1       0            2      2  23.4500
889       1  26.0      0       1            0      0  30.0000
890       3  32.0      0       1            1      0   7.7500

[891 rows x 7 columns]

In [ ]:
cross_val_score(DecisionTreeClassifier(),X,y)

array([0.73743017, 0.78651685, 0.80898876, 0.75280899, 0.79213483])

In [ ]:
cross_val_score(RandomForestClassifier(),X,y)

array([0.76536313, 0.80898876, 0.84269663, 0.7752809 , 0.8258427 ])

In [26]:
from sklearn.datasets import load_wine
data=load_wine()
df=pd.DataFrame(data.data,columns=data.feature_names)
df['target']=data.target

In [27]:
df.sample(5)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
80,12.00,0.92,2.00,19.0,86.0,2.42,2.26,0.30,1.43,2.50,1.38,3.12,278.0,1
37,13.05,1.65,2.55,18.0,98.0,2.45,2.43,0.29,1.44,4.25,1.12,2.51,1105.0,0
166,13.45,3.70,2.60,23.0,111.0,1.70,0.92,0.43,1.46,10.68,0.85,1.56,695.0,2
95,12.47,1.52,2.20,19.0,162.0,2.50,2.27,0.32,3.28,2.60,1.16,2.63,937.0,1
54,13.74,1.67,2.25,16.4,118.0,2.60,2.90,0.21,1.62,5.85,0.92,3.20,1060.0,0

<h1>exercise

In [1]:
import pandas as pd
from sklearn.datasets import load_wine
data=load_wine()
df=pd.DataFrame(data.data,columns=data.feature_names)

In [2]:
df.sample(5)

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
72     13.49        1.66  2.24  ...  0.98                          2.78    472.0
119    12.00        3.43  2.00  ...  0.93                          3.05    564.0
47     13.90        1.68  2.12  ...  0.91                          3.33    985.0
127    11.79        2.13  2.78  ...  0.97                          2.44    466.0
160    12.36        3.83  2.38  ...  0.56                          1.58    520.0

[5 rows x 13 columns]

In [3]:
df['target']=data.target
df.head()

   alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0    14.23        1.71  2.43  ...                          3.92   1065.0       0
1    13.20        1.78  2.14  ...                          3.40   1050.0       0
2    13.16        2.36  2.67  ...                          3.17   1185.0       0
3    14.37        1.95  2.50  ...                          3.45   1480.0       0
4    13.24        2.59  2.87  ...                          2.93    735.0       0

[5 rows x 14 columns]

In [4]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [5]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('target',axis=1),df['target'],test_size=0.2)

In [6]:
model_g=GaussianNB()
model_nm=MultinomialNB()

In [7]:
model_g.fit(x_train,y_train)

GaussianNB()

In [11]:
model_g.score(x_test,y_test)

0.9722222222222222

In [10]:
model_g.predict(x_test)

array([0, 2, 1, 2, 1, 2, 2, 0, 2, 1, 1, 2, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2,
       0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 1, 0])

In [12]:
model_nm.fit(x_train,y_train)

MultinomialNB()

In [13]:
model_nm.score(x_test,y_test)

0.8888888888888888