In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
df=pd.read_csv(r"C:\Users\Jeevan kumar\Videos\Handle_missing_data_1_Exercise\Handle_missing_data_1_Exercise\fruits_data.csv")
df.head()

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.0,65.0,184.0,NaN
1,01-02-2022,237.0,50.0,72.0,173.0,72.0
2,01-03-2022,259.0,NaN,NaN,NaN,93.0
3,01-04-2022,NaN,41.0,75.0,175.0,74.0
4,01-05-2022,240.0,48.0,NaN,185.0,84.0

In [4]:
df.isnull().sum()

date               0
apple(1kg)         2
banana(1 dozen)    2
grapes(1kg)        3
mango(1kg)         2
Water Melons(1)    2
dtype: int64

In [5]:
df.describe()

       apple(1kg)  banana(1 dozen)  grapes(1kg)  mango(1kg)  Water Melons(1)
count    8.000000         8.000000     7.000000    8.000000         8.000000
mean   238.500000        45.625000    69.285714  183.750000        86.500000
std      9.007933         3.248626     3.728909    9.315885         9.335034
min    230.000000        41.000000    65.000000  173.000000        72.000000
25%    233.500000        44.000000    66.000000  174.750000        81.500000
50%    236.500000        46.000000    70.000000  184.500000        89.500000
75%    240.000000        48.000000    71.500000  188.750000        93.000000
max    259.000000        50.000000    75.000000  198.000000        97.000000

In [6]:
df['apple(1kg)'].mean()

np.float64(238.5)

In [27]:
df['apple(1kg)'] = df['apple(1kg)'].fillna(round(df['apple(1kg)'].mean(), 2)).round(2)
df['banana(1 dozen)'] = df['banana(1 dozen)'].fillna(round(df['banana(1 dozen)'].mean(), 2)).round(2)
df['grapes(1kg)'] = df['grapes(1kg)'].fillna(round(df['grapes(1kg)'].mean(), 2)).round(2)
df['mango(1kg)'] = df['mango(1kg)'].fillna(round(df['mango(1kg)'].mean(), 2)).round(2)

In [28]:
df.head()

,date,apple(1kg),banana(1 dozen),grapes(1kg),mango(1kg),Water Melons(1)
0,01-01-2022,230.0,46.00,65.00,184.00,NaN
1,01-02-2022,237.0,50.00,72.00,173.00,72.0
2,01-03-2022,259.0,45.62,69.29,183.75,93.0
3,01-04-2022,238.5,41.00,75.00,175.00,74.0
4,01-05-2022,240.0,48.00,69.29,185.00,84.0