In [1]:
import pandas as pd

df=pd.read_csv(r"C:\Users\Jeevan kumar\Downloads\Melbourne_housing_FULL.csv")
df.sample(5)

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
34832,Westmeadows,2/8 Forman St,4,u,689000.0,S,YPA,24/02/2018,16.5,3049.0,...,NaN,NaN,NaN,NaN,NaN,Hume City Council,NaN,NaN,Northern Metropolitan,2474.0
188,Albert Park,8 Kerferd Pl,4,h,NaN,SP,Marshall,28/05/2016,3.3,3206.0,...,2.0,0.0,230.0,185.0,1900.0,Port Phillip City Council,-37.8420,144.9580,Southern Metropolitan,3280.0
35,Abbotsford,78 Yarra St,3,h,1176500.0,S,LITTLE,16/07/2016,2.5,3067.0,...,1.0,1.0,138.0,105.0,1890.0,Yarra City Council,-37.8021,144.9965,Northern Metropolitan,4019.0
10877,Yarraville,101 Roberts St,3,h,1050000.0,S,hockingstuart,4/06/2016,7.0,3013.0,...,2.0,1.0,462.0,132.0,1960.0,Maribyrnong City Council,-37.8128,144.8695,Western Metropolitan,6543.0
12828,Glen Huntly,8/131 Grange Rd,1,u,260000.0,SP,Woodards,13/05/2017,10.4,3163.0,...,1.0,1.0,1162.0,44.0,1965.0,Glen Eira City Council,-37.8911,145.0451,Southern Metropolitan,2403.0

In [3]:
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [7]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [8]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [17]:
df1=df[['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 
               'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']]

In [10]:
df1.sample(5)

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
24780,Wantirna South,3,h,S,iTRAK,Eastern Metropolitan,7082.0,14.7,Knox City Council,3.0,2.0,2.0,767.0,166.0,945000.0
3183,Chadstone,3,h,S,Buxton,Southern Metropolitan,3582.0,13.6,Monash City Council,3.0,1.0,2.0,620.0,88.0,1301000.0
31926,Mill Park,4,h,SP,Ray,Northern Metropolitan,10529.0,17.9,Whittlesea City Council,4.0,2.0,2.0,750.0,NaN,775000.0
6262,Malvern,3,t,PI,Marshall,Southern Metropolitan,4675.0,7.4,Stonnington City Council,3.0,2.0,1.0,227.0,181.0,1390000.0
31957,Mount Waverley,3,h,S,Jellis,Eastern Metropolitan,13366.0,14.2,Monash City Council,3.0,1.0,2.0,749.0,NaN,NaN

In [20]:
df['Propertycount']=df['Propertycount'].fillna(0)
df['Distance']=df['Distance'].fillna(0)
df['Bedroom2']=df['Bedroom2'].fillna(0)
df['Bathroom']=df['Bathroom'].fillna(0)
df['Car']=df['Car'].fillna(0)

In [21]:
df1['Landsize'] = df1['Landsize'].fillna(df1['Landsize'].mean())

In [22]:
df1['BuildingArea']=df['BuildingArea'].fillna(df1['BuildingArea'].mean())

In [25]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             0
Postcode             1
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        0
dtype: int64

In [24]:
df1.dropna(inplace=True)

In [27]:
data_set=pd.get_dummies(df1, drop_first=True)
data_set.sample(5)

,Rooms,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,Suburb_Aberfeldie,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
18956,3,9264.0,7.5,3.0,1.0,1.0,393.000000,160.2564,1620000.0,False,...,False,False,False,False,False,False,False,False,False,False
21985,3,6162.0,20.0,3.0,1.0,2.0,593.598993,160.2564,925000.0,False,...,False,False,False,False,False,False,False,False,False,False
22249,2,4605.0,10.9,2.0,1.0,1.0,593.598993,160.2564,466000.0,False,...,False,False,False,False,False,True,False,False,False,False
12591,2,5051.0,9.3,2.0,1.0,1.0,534.000000,160.2564,1104000.0,False,...,False,False,False,False,False,False,False,False,False,False
5222,2,11308.0,4.6,2.0,1.0,1.0,1089.000000,76.0000,580000.0,False,...,False,False,False,False,False,False,False,False,False,False

In [28]:
data_set.shape

(20423, 712)

In [32]:
x=data_set.drop('Price', axis=1)
y=data_set['Price']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=2)

In [33]:
model=LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [34]:
model.score(x_test,y_test)

0.6800616887114233

In [35]:
from sklearn import linear_model
lesso=linear_model.Lasso(alpha=50,max_iter=100,tol=0.1)
lesso.fit(x_train,y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [36]:
lesso.score(x_test,y_test)

0.6825006799799274

In [39]:
from sklearn.linear_model import  Ridge  
ridge=Ridge(alpha=50,max_iter=100,tol=0.1)
ridge.fit(x_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [40]:
ridge.score(x_test,y_test)

0.6728845190612603