In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data/home_prices.csv')
df.head()

   area_sqr_ft  bedrooms color  price_lakhs
0         3774         2   Red          216
1         1460         3  Gray           88
2         1894         4  Gray          147
3         1730         2  Blue           84
4         1695         1  Blue           77

# Feature selection using Correlation

In [3]:
df.area_sqr_ft.corr(df.price_lakhs)

np.float64(0.9453650260417832)

In [5]:
df_encoded=pd.get_dummies(df,columns=['color'],drop_first=True,dtype=int)
df_encoded.head()

,area_sqr_ft,bedrooms,price_lakhs,color_Gray,color_Green,color_Red,color_White,color_Yellow
0,3774,2,216,0,0,1,0,0
1,1460,3,88,1,0,0,0,0
2,1894,4,147,1,0,0,0,0
3,1730,2,84,0,0,0,0,0
4,1695,1,77,0,0,0,0,0

In [7]:
cm=df_encoded.corr()
cm

,area_sqr_ft,bedrooms,price_lakhs,color_Gray,color_Green,color_Red,color_White,color_Yellow
area_sqr_ft,1.000000,0.185810,0.945365,-0.068944,-0.032012,0.059055,0.063827,-0.037819
bedrooms,0.185810,1.000000,0.439445,0.040882,-0.120207,-0.004177,-0.023676,0.015286
price_lakhs,0.945365,0.439445,1.000000,-0.040565,-0.041959,0.045803,0.051122,-0.046673
color_Gray,-0.068944,0.040882,-0.040565,1.000000,-0.214409,-0.230990,-0.205931,-0.217205
color_Green,-0.032012,-0.120207,-0.041959,-0.214409,1.000000,-0.190117,-0.169493,-0.178771
color_Red,0.059055,-0.004177,0.045803,-0.230990,-0.190117,1.000000,-0.182600,-0.192596
color_White,0.063827,-0.023676,0.051122,-0.205931,-0.169493,-0.182600,1.000000,-0.171703
color_Yellow,-0.037819,0.015286,-0.046673,-0.217205,-0.178771,-0.192596,-0.171703,1.000000

In [ ]:
round(abs(cm.price_lakhs),2)# > 0.2 features are not important refering to price_lakhs

area_sqr_ft     0.95
bedrooms        0.44
price_lakhs     1.00
color_Gray      0.04
color_Green     0.04
color_Red       0.05
color_White     0.05
color_Yellow    0.05
Name: price_lakhs, dtype: float64

In [14]:
cm[cm.price_lakhs>.2].index

Index(['area_sqr_ft', 'bedrooms', 'price_lakhs'], dtype='str')

In [15]:
selected_features=cm[cm.price_lakhs>.2].index.drop('price_lakhs')

In [ ]:
selected_features

Index(['area_sqr_ft', 'bedrooms'], dtype='str')

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

x=df[selected_features]
y=df.price_lakhs

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LinearRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R2 Score: {r2}')

Mean Squared Error: 76.63332198278805
R2 Score: 0.9689466488379601

## Scenorios where not to use correlation for feature selection:  
1. Non-Linear relation  
2. presence of outliers  
3. many categorical variables in data frame  
4. correlation VS causation